### ISSUE TITLE
xdoc/top can't be included at the top of misc/assert.lisp

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#362] opened 2015-04-01 20:08 UTC
I was going to document assert.lisp, but it appears that including `xdoc/top` at the top of `misc/assert.lisp` causes a bizarre error (scroll to end):

```
   | ACL2 !>> "ACL2"
   | ACL2 !>>
   | Summary
   | Form:  ( INCLUDE-BOOK "std/portcullis" ...)
   | Rules: NIL
   | Time:  0.10 seconds (prove: 0.00, print: 0.00, other: 0.10)
   |  "/import/siete-aus-verif4/dlrager/sw/acl2-edit/books/std/portcullis.lisp"
   | ACL2 !>>Bye.
   |  :EOF
   | ACL2 !>
   | ACL2 Version 7.0.  Level 2.  Cbd 
   | "/import/siete-aus-verif4/dlrager/sw/acl2-edit/books/misc/".
   | System books directory 
   | "/import/siete-aus-verif4/dlrager/sw/acl2-edit/books/".
   | Type :help for help.
   | Type (good-bye) to quit completely out of ACL2.
   | 
   | ACL2 !>> "ACL2"
   | ACL2 !>>Bye.
   |  :EOF
   | ACL2 !> :CONTINUE
   | ACL2 !>
   | Summary
   | Form:  ( INCLUDE-BOOK "xdoc/top" ...)
   | Rules: NIL
   | Time:  0.04 seconds (prove: 0.00, print: 0.00, other: 0.04)
   | "/import/siete-aus-verif4/dlrager/sw/acl2-edit/books/xdoc/top.lisp"
   | 
   | Summary
   | Form:  ( DEFUN ASSERT!-BODY ...)
   | Rules: ((:FAKE-RUNE-FOR-TYPE-SET NIL))
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | ASSERT!-BODY
   | 
   | Summary
   | Form:  ( DEFMACRO ASSERT! ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | ASSERT!
   | 
   | Summary
   | Form:  ( DEFUN ASSERT-TEST1 ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | Summary
   | Form:  ( MAKE-EVENT (LET ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | ASSERT-TEST1
   | T
   | 
   | Summary
   | Form:  ( INCLUDE-BOOK "eval" ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | "/import/siete-aus-verif4/dlrager/sw/acl2-edit/books/misc/eval.lisp"
   | 
   | 
   | ACL2 Error in ASSERT!:  Assertion failed:
   | (EQUAL 3 4)
   | 
   | 
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  Error in MAKE-EVENT on
   | behalf of
   |   (ASSERT! (EQUAL 3 4)
   |            (DEFUN ASSERT-TEST2 (X) X))
   | from expansion of:
   |   (LET ((ASSERTION (EQUAL 3 4)))
   |        (ER-PROGN (IF ASSERTION (VALUE NIL)
   |                      (ER SOFT 'ASSERT!
   |                          "Assertion failed:~%~x0" '#))
   |                  (VALUE '(DEFUN ASSERT-TEST2 # X))))
   | (See :DOC set-iprint to be able to see elided values in this message.)
   | 
   | 
   | Summary
   | Form:  ( MAKE-EVENT (LET ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  ( MAKE-EVENT (STATE-GLOBAL-LET* ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | Summary
   | Form:  ( MAKE-EVENT (QUOTE ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | T
   | 
   | Summary
   | Form:  ( DEFUN ASSERT-TEST2 ...)
   | Rules: ((:FAKE-RUNE-FOR-TYPE-SET NIL))
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | ASSERT-TEST2
   | 
   | Summary
   | Form:  ( MAKE-EVENT (LET ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | :SUCCESS
   | 
   | 
   | ACL2 Error in ASSERT!:  Assertion failed:
   | (EQUAL (APPEND '(A B C) '(D E F)) '(A B))
   | 
   | 
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  Error in MAKE-EVENT on
   | behalf of
   |   (ASSERT! (EQUAL (APPEND '(A B C) '(D E F))
   |                   '(A B)))
   | from expansion of:
   |   (LET ((ASSERTION (EQUAL (APPEND # #) '#)))
   |        (ER-PROGN (IF ASSERTION (VALUE NIL)
   |                      (ER SOFT 'ASSERT!
   |                          "Assertion failed:~%~x0" '#))
   |                  (VALUE '(VALUE-TRIPLE :SUCCESS))))
   | (See :DOC set-iprint to be able to see elided values in this message.)
   | 
   | 
   | Summary
   | Form:  ( MAKE-EVENT (LET ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  ( MAKE-EVENT (STATE-GLOBAL-LET* ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | Summary
   | Form:  ( MAKE-EVENT (QUOTE ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | T
   | 
   | 
   | ACL2 Error in ASSERT!:  Assertion failed:
   | (EQUAL (ACCESS-COMMAND-TUPLE-FORM (CDDR (CAR (SCAN-TO-COMMAND #))))
   |        '(EXIT-BOOT-STRAP-MODE))
   | (See :DOC set-iprint to be able to see elided values in this message.)
   | 
   | 
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  Error in MAKE-EVENT on
   | behalf of
   |   (ASSERT! (EQUAL (ACCESS-COMMAND-TUPLE-FORM (CDDR (CAR #)))
   |                   '(EXIT-BOOT-STRAP-MODE)))
   | from expansion of:
   |   (LET ((ASSERTION (EQUAL (ACCESS-COMMAND-TUPLE-FORM #)
   |                           '#)))
   |        (ER-PROGN (IF ASSERTION (VALUE NIL)
   |                      (ER SOFT 'ASSERT!
   |                          "Assertion failed:~%~x0" '#))
   |                  (VALUE '(VALUE-TRIPLE :SUCCESS))))
   | (See :DOC set-iprint to be able to see elided values in this message.)
   | 
   | 
   | Summary
   | Form:  ( MAKE-EVENT (LET ...) ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( MAKE-EVENT (LET ...) ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  ( MAKE-EVENT (ER-LET* ...))
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( MAKE-EVENT (ER-LET* ...)):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  (CERTIFY-BOOK "assert" ...)
   | Rules: NIL
   | Time:  0.07 seconds (prove: 0.00, print: 0.00, other: 0.07)
   | 
   | ACL2 Error in (CERTIFY-BOOK "assert" ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
   | ; 0.07 seconds realtime, 0.06 seconds runtime
   | ; (3,372,752 bytes allocated).
   | ACL2 !>Bye.
   | Exit code from ACL2 is 0
   | assert.cert seems to be missing
```

Diff for assert.lisp:
```

bash-4.1$ git diff assert.lisp
diff --git a/books/misc/assert.lisp b/books/misc/assert.lisp
index 0e8606f..b47f6a4 100644
--- a/books/misc/assert.lisp
+++ b/books/misc/assert.lisp
@@ -11,6 +11,16 @@
 
 (in-package "ACL2")
 
+(include-book "xdoc/top" :dir :system)
+
+;; (defxdoc assert!
+;;   :parents (errors assert$)
+;;   :short "Form of assert that allows just testing a single value"
+;;   :long "Example usage:
+;;  @({
+;;  (assert! (equal 3 3))
+;;  })")
+
 (defun assert!-body (assertion form)
 
 ; Note that assertion should evaluate to a single non-stobj value.  See also
bash-4.1$ 
```

**Comment by MattKaufmann** [comment] 2015-04-01 20:29
I've taken a look, and the problem is a bit subtle.  The failure
occurs with this form in books/misc/assert.lisp, when attempting
certification with cert.pl.

    (local (make-event
            (er-let* ((c (getenv$ "ACL2_CUSTOMIZATION" state)))
              (value
               (if (and c (not (equal c "NONE")))
                   `(value-triple
                     (cw "SKIPPING due to ACL2_CUSTOMIZATION=~x0~%" ,c))
                 '(assert! (equal (access-command-tuple-form
                                   (cddr (car (scan-to-command (w state)))))
                                  '(exit-boot-strap-mode))))))))

I created the following much simpler book, and certified it with
cert.pl.

      (in-package "ACL2")

      (include-book "xdoc/top" :dir :system)

      (make-event `(value-triple ',(access-command-tuple-form
                                    (cddr (car (scan-to-command (w state)))))))

The log shows that the value-triple form evaluates to the following
command tuple form.

    (INCLUDE-BOOK "std/portcullis"
                  :DIR :SYSTEM)

But it should have evaluated to:

    (EXIT-BOOT-STRAP-MODE)

This says to me that somewhere under xdoc/top.lisp, there is a call of
LD (or LD-FN, etc.).  I've considered making that illegal, since LD is
only intended to be called at the top level.

We could simply remove that failing form from books/misc/assert.lisp,
but I think it would be better to get to the bottom of why
xdoc/top.lisp is laying down a command tuple during certification.
I'm assigning to Jared since I think that's Jared's stuff; he's
welcome to contact me to work with him on this issue.

**Comment by MattKaufmann** [comment] 2015-04-01 21:28
Ah, I see now what happened.  When cert.pl was used, then this form
was evaluated before the certify-book command:

    (acl2::ld "xdoc/top.port" :dir :system :ld-missing-input-ok t)

I was hoping we can solve this by adding file assert.acl2, containing
just the form `(ubt! 1)`.  Unfortunately, cert.pl puts the .acl2 form
first, rather than last, so the above acl2::ld call still takes place
before certification.

So the best solution might be simply to comment out the offending
event that I mentioned in my first comment on this Issue, saying
that it's no longer appropriate because cert.pl loads .port files.
Better yet might be to tell cert.pl not to include .port files for
this book, but I didn't see a way to do that using `cert.pl --help` or
looking at :doc cert.pl etc.  I'm assigning to David, who is welcome
to close this Issue or to ask me to make the change I suggest above.

**Comment by ragerdl** [comment] 2015-04-01 21:33
@MattKaufmann You have my "blessing" to go ahead and make the change.  Thanks!

**Comment by MattKaufmann** [comment] 2015-04-01 21:59
Change completed with commit 5b09a8d548929da413ffabf70d58abec7228cc0b.

**Closed by MattKaufmann** 2015-04-01 21:59 UTC
Labels: Priority: Contentious, Usability
