### ISSUE TITLE
ACL2(r) failing certifying books/hacking/redefun.lisp

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#821] opened 2018-02-10 05:57 UTC
I got below error when certifying acl2r:

**CERTIFICATION FAILED** for /.../books/hacking/redefun.lisp

   | "-*- Mode: auto-revert -*-"
   | /.../books/hacking
   | HOST: mala
   | 
   | Environment variables:
   | ACL2_CUSTOMIZATION=NONE
   | ACL2_SYSTEM_BOOKS=/.../books
   | ACL2=/.../saved_acl2r
   | 
   | Temp lisp file:
   | (acl2::value :q)
   | (acl2::in-package "ACL2")
   | ; see github issue #638 (waterfall-parallelism and profiling): 
   | #+(and hons (not acl2-par)) (profile-fn 'prove)
   | #+(and hons (not acl2-par)) (profile-fn 'certify-book-fn)
   | (acl2::lp)
   | (set-debugger-enable :bt)
   | (acl2::in-package "ACL2")
   | 
   | (set-ld-error-action (quote (:exit 1)) state)
   | (set-inhibit-output-lst (list (quote prove) (quote proof-tree) (quote warning) (quote observation) (quote event) (quote history)))
   | 
   | (acl2::assign acl2::get-internal-time-as-realtime acl2::t)
   | #-cmucl (acl2::gc-verbose t)
   | ; instructions from .acl2 file redefun.acl2:
   | (in-package "ACL2")
   | (ld "hacker-pkg.lsp")
   | 
   | 
   | 
   | ; Prevent reset-prehistory while loading .port files
   | (acl2::assign acl2::skip-reset-prehistory acl2::t)
   | ; portculli for included books:
   | #!ACL2 (set-ld-error-action (quote :continue) state)
   | 
   | ; certify-book command flags: ? t
   | #!ACL2 (er-progn (time$ (certify-book "redefun" ? t  ))
   |                                  (value (prog2$ #+hons (memsum)
   |                                                  #-hons nil
   |                                                  (exit 43))))
   | --- End temp lisp file ---
   | 
   | TARGET: hacking/redefun
   | STEP: certify
   | Start of output:
   | 
   | Welcome to Clozure Common Lisp Version 1.11-r16635  (LinuxX8664)!
   | 
   |  ACL2 Version 8.0(r) built February 9, 2018  16:58:35.
   |  Copyright (C) 2017, Regents of the University of Texas
   |  ACL2 comes with ABSOLUTELY NO WARRANTY.  This is free software and you
   |  are welcome to redistribute it under certain conditions.  For details,
   |  see the LICENSE file distributed with ACL2.
   | 
   |  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   |  + WARNING: This is NOT an ACL2 release; it is a development snapshot  +
   |  + (git commit hash: 7bce568fc463c31ab35b9c6d8ce9d79e6bea92bf).        +
   |  + On rare occasions development snapshots may be incomplete, fragile, +
   |  + or unable to pass the usual regression tests.                       +
   |  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
   | 
   |  Initialized with (INITIALIZE-ACL2 'INCLUDE-BOOK *ACL2-PASS-2-FILES*).
   |  See the documentation topic note-8-0 for recent changes.
   |  Note: We have modified the prompt in some underlying Lisps to further
   |  distinguish it from the ACL2 prompt.
   | 
   | ACL2 Version 8.0(r).  Level 1.  Cbd 
   | "/.../books/hacking/".
   | System books directory 
   | "/.../books/".
   | Type :help for help.
   | Type (good-bye) to quit completely out of ACL2.
   | 
   | ACL2(r) !>
   | Exiting the ACL2 read-eval-print loop.  To re-enter, execute (LP).
   | ? #<Package "ACL2">
   | ? PROVE
   | ? CERTIFY-BOOK-FN
   | ? 
   | ACL2 Version 8.0(r).  Level 1.  Cbd 
   | "/.../books/hacking/".
   | System books directory 
   | "/.../books/".
   | Type :help for help.
   | Type (good-bye) to quit completely out of ACL2.
   | 
   | ACL2(r) !><state>
   | ACL2(r) !> "ACL2"
   | ACL2(r) !> (:EXIT 1)
   | ACL2(r) !> (PROVE PROOF-TREE
   |         WARNING OBSERVATION EVENT HISTORY)
   | ACL2(r) !> T
   | ACL2(r) !>NIL
   | ACL2(r) !> "ACL2"
   | ACL2(r) !>
   | ACL2 Version 8.0(r).  Level 2.  Cbd 
   | "/.../books/hacking/".
   | System books directory 
   | "/.../books/".
   | Type :help for help.
   | Type (good-bye) to quit completely out of ACL2.
   | 
   | ACL2(r) !>>
   | Summary
   | Form:  ( DEFPKG "ACL2-HACKER" ...)
   | Rules: NIL
   | Time:  0.03 seconds (prove: 0.00, print: 0.00, other: 0.03)
   |  "ACL2-HACKER"
   | ACL2(r) !>>Bye.
   |  :EOF
   | ACL2(r) !> T
   | ACL2(r) !> :CONTINUE
   | ACL2(r) !>:INVISIBLE
   | T
   | 
   | 
   | ACL2 Error in ( DEFUN CHK-ACCEPTABLE-REDEFUN ...):  CHK-ACCEPTABLE-DEFUNS
   | takes 5 arguments but in the call 
   | (CHK-ACCEPTABLE-DEFUNS (LIST DEF) CTX WRLD STATE) it is given 4 arguments.
   | The formal parameters list for CHK-ACCEPTABLE-DEFUNS is 
   | (LST CTX WRLD STATE STD-P).
   | 
   | 
   | Summary
   | Form:  ( DEFUN CHK-ACCEPTABLE-REDEFUN ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( DEFUN CHK-ACCEPTABLE-REDEFUN ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  (CERTIFY-BOOK "redefun" ...)
   | Rules: NIL
   | Time:  0.02 seconds (prove: 0.00, print: 0.00, other: 0.02)
   | 
   | ACL2 Error in (CERTIFY-BOOK "redefun" ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
   | ; 0.02 seconds realtime, 0.01 seconds runtime
   | ; (411,312 bytes allocated).
   | ACL2(r) !>Bye.
   | Exit code from ACL2 is 0
   | redefun.cert seems to be missing

**CERTIFICATION FAILED** for /.../books/hacking/redefun.lisp

Does this look like a real problem?

**Comment by kini** [comment] 2018-02-10 06:01
On 02/09/2018 09:57 PM, Yan Peng wrote:
> I got below error when certifying acl2r:
> 
> *CERTIFICATION FAILED* for /.../books/hacking/redefun.lisp

Isn't that book excluded from the ACL2(r) regression?  There's a comment at the
top saying

  ; cert_param: (non-acl2r)

So I guess it's not supposed to be working under ACL2(r).

What commit do you have checked out, and what command did you run which led to
this error?

-Keshav

**Comment by pennyan** [comment] 2018-02-10 06:17
Hi @kini, the commit is 7bce568fc463c31ab35b9c6d8ce9d79e6bea92bf. I went inside books and did "make all ACL2=../saved_acl2r"

**Comment by pennyan** [comment] 2018-02-10 07:22
Hi @kini , the problem goes away when I use the absolute path for ACL2=... Probably it's not picking up the right ACL2 and somehow that can cause problems?

**Comment by kini** [comment] 2018-02-10 08:43
On 02/09/2018 11:22 PM, Yan Peng wrote:
> Hi @kini <https://github.com/kini> , the problem goes away when I use the
> absolute path for ACL2=... Probably it's not picking up the right ACL2 and
> somehow that can cause problems?

Hmm, yeah, that's happened to me before.  I usually write `make
ACL2=$PWD/../saved_acl2 [...]` instead of `make ACL2=../saved_acl2 [...]` for
that reason.

By the way, thanks to your report I've now learned that cert_param comments
only apply when you build using `make` from the community books makefile.
cert.pl doesn't seem to actually utilize them itself.  That seems like a
potential improvement to the build system that could be made.

-Keshav

**Comment by solswords** [comment] 2018-02-10 15:31
FWIW, I think the reason the cert_param restrictions are handled in the
GNUMakefile rather than in cert.pl itself (though cert.pl is the thing that
makes the lists of what books depend on what cert_params) is that it makes
a lot more sense to me to change what an abstract Makefile target like
"all" or "basic" means based on what books are certifiable, rather than to
refuse to try and certify a book that the user has specifically requested
(which is all you can do with cert.pl).  Even with the Makefile, if you
list a specific book.cert target on the command line, it'll try and make
that regardless of whether it depends on a feature you don't have.

**Comment by kini** [comment] 2018-02-10 16:19
Well, with cert.pl you can specify an arbitrary number of books on the command line, so it could still be useful to filter out some of them; and if one is really hoping for a book to build on, say, ACL2(r), maybe one should be expected to have removed the "non-acl2r" cert_param from the book first. But I see your point.

**Comment by kini** [comment] 2018-02-10 23:52
@pennyan should we close this issue, or is there something else that should be done?

**Comment by pennyan** [comment] 2018-02-10 23:57
@kini  Thank you for mentioning the $PWD stuff. I think it's good for now. I will close this issue!

**Closed** 2018-02-10 23:57 UTC
