### ISSUE TITLE
redef+ update is leading to failure of books/hacking/progn-bang-enh

### ISSUE THREAD

**Issue by pmanolios** [acl2/acl2#1275] opened 2021-06-22 19:11 UTC
After @MattKaufmann 's update to fix the redef+ bug,  see commit bca83d0, the following book fails to certify:

books/hacking/progn-bang-enh

**Comment by MattKaufmann** [comment] 2021-06-22 19:24
@pmanolios I certified that book successfully before committing and pushing the commit you mentioned (as part of a fresh regression-everything, as usual).  That was on a Mac, so just now I certified it successfully on Linux.  If you can reproduce the certification error using saved_acl2 built on the latest sources, then please email me the .cert.out file.  Otherwise maybe it would be best for you to close this Issue.

**Comment by MattKaufmann** [comment] 2021-06-22 20:10
@pmanolios I got the log from @mister-walter -- looks like SBCL may have caught something that CCL missed.  I'm looking into it now.

**Comment by MattKaufmann** [comment] 2021-06-23 02:36
Closing after @pmanolios confirmed that this update fixed the problem.

**Closed by MattKaufmann** 2021-06-23 02:36 UTC
