### ISSUE TITLE
error when cleaning, possibly for mliawa books

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#387] opened 2015-05-23 17:43 UTC
Bob Boyer sent the following bug report, which I'm posting
with his permission.  He gave this command:

    cd ~/acl2 ; time nice make -j 4 regression-everything-fresh >>& acl2.log

Below is the log.  Since one of the errors is about mliawa, I'm assigning to Jared (I figure he can always unsaying himself).

    ACL2_WD is /Users/boyer/acl2
    cd books ; /Applications/Xcode.app/Contents/Developer/usr/bin/make -k
    ACL2=/Users/boyer/acl2/saved_acl2 moreclean
    ACL2_SYSTEM_BOOKS is /Users/boyer/acl2/books
    Scanning for books...

    real 0m2.357s
    user 0m0.201s
    sys 0m0.290s
    Scanning for dependencies...

    real 0m7.698s
    user 0m6.486s
    sys 0m0.800s
    Done scanning.
    Reading book deps Makefile-deps created on Sat May 23 11:04:53 CDT 2015
    Determining ACL2 features (for ACL2 = /Users/boyer/acl2/saved_acl2)
    Determining whether Glucose is installed
    ACL2_HAS_HONS     := 1
    ACL2_HAS_ANSI     := 1
    ACL2_HAS_PARALLEL :=
    ACL2_HAS_REALS    :=
    ACL2_COMP_EXT     := dx64fsl
    ACL2_HOST_LISP    := CCL
    OS_HAS_GLUCOSE    :=
    USE_QUICKLISP     :=
    Done with features.
    Excluding books that need Glucose: [centaur/aig/aig-sat-tests.cert
    centaur/esim/tests/add.cert centaur/esim/tests/common.cert
    centaur/esim/tests/divide.cert centaur/esim/tests/idiv.cert
    centaur/esim/tests/multiply.cert centaur/esim/tests/regs.cert
    centaur/esim/tests/subtract.cert centaur/esim/tutorial/boothmul.cert
    centaur/sv/tutorial/boothpipe.cert ]
    Excluding ACL2(r)-only books: [nonstd/fft/fft-trig-with-axioms.cert
    nonstd/fft/fft-trig.cert nonstd/integrals/continuous-function.cert
    nonstd/integrals/equivalence-continuous-function.cert
    nonstd/integrals/equivalence-ftc.cert
    nonstd/integrals/equivalence-integrals.cert nonstd/integrals/ftc-1.cert
    nonstd/integrals/ftc-2.cert nonstd/integrals/integrable-functions.cert
    nonstd/integrals/integral-of-polynomials.cert
    nonstd/integrals/integration-composition-equivalences.cert
    nonstd/integrals/integration-composition.cert
    nonstd/integrals/make-partition.cert
    nonstd/integrals/split-integral-by-subintervals.cert
    nonstd/nsa/alternating-series.cert nonstd/nsa/chain-rule.cert
    nonstd/nsa/complex-polar.cert nonstd/nsa/continuity-product.cert
    nonstd/nsa/continuity.cert nonstd/nsa/derivative-raise.cert
    nonstd/nsa/derivatives-composition.cert nonstd/nsa/derivatives.cert
    nonstd/nsa/equivalence-continuity.cert
    nonstd/nsa/equivalence-derivatives-composition.cert
    nonstd/nsa/equivalence-derivatives.cert nonstd/nsa/equivalence-limits.cert
    nonstd/nsa/exp-continuous.cert nonstd/nsa/exp-sum.cert nonstd/nsa/exp.cert
    nonstd/nsa/factorial.cert nonstd/nsa/intervals.cert
    nonstd/nsa/inverse-derivatives.cert nonstd/nsa/inverse-monotone.cert
    nonstd/nsa/inverse-square.cert nonstd/nsa/inverse-trig.cert
    nonstd/nsa/inverses.cert nonstd/nsa/ln.cert nonstd/nsa/next-integer.cert
    nonstd/nsa/norm.cert nonstd/nsa/nsa.cert nonstd/nsa/overspill-proof.cert
    nonstd/nsa/overspill-test.cert nonstd/nsa/overspill.cert
    nonstd/nsa/raise.cert nonstd/nsa/sine.cert nonstd/nsa/sqrt.cert
    nonstd/nsa/trig-approx.cert nonstd/nsa/trig.cert
    nonstd/polynomials/polynomial-calculus.cert
    nonstd/polynomials/polynomial-defuns.cert
    nonstd/polynomials/polynomial-lemmas.cert nonstd/sqrt/no-sqrt.cert
    nonstd/transcendentals/nested-intervals-revised.cert
    nonstd/transcendentals/nested-intervals.cert
    nonstd/transcendentals/reals-are-uncountable-1.cert
    nonstd/transcendentals/reals-are-uncountable-2.cert
    nonstd/workshops/1999/analysis/continuity.cert
    nonstd/workshops/1999/analysis/derivatives.cert
    nonstd/workshops/1999/analysis/exercise1.cert
    nonstd/workshops/1999/analysis/exercise2.cert
    nonstd/workshops/1999/analysis/exercise3.cert
    nonstd/workshops/1999/analysis/exercise4.cert
    nonstd/workshops/1999/analysis/exercise5.cert
    nonstd/workshops/1999/analysis/exercise6.cert
    nonstd/workshops/1999/analysis/exercise7.cert
    nonstd/workshops/1999/analysis/exercise8.cert
    nonstd/workshops/1999/calculus/book/between-i-close-implies-i-close.cert
    nonstd/workshops/1999/calculus/book/between-limited-implies-limited.cert
    nonstd/workshops/1999/calculus/book/defaxioms.cert
    nonstd/workshops/1999/calculus/book/equal-riemann-rcfn-refinement-reduction.cert
    nonstd/workshops/1999/calculus/book/ftoc-lemma.cert
    nonstd/workshops/1999/calculus/book/fundamental-theorem-of-calculus.cert
    nonstd/workshops/1999/calculus/book/i-close-implies-abs-difference-small.cert
    nonstd/workshops/1999/calculus/book/i-limited-rcfn.cert
    nonstd/workshops/1999/calculus/book/i-small-maxlist-abslist-difflist-maps.cert
    nonstd/workshops/1999/calculus/book/integral-rcfn-equal-if-i-close.cert
    nonstd/workshops/1999/calculus/book/integral-rcfn-lemmas.cert
    nonstd/workshops/1999/calculus/book/integral-rcfn-quotient-between-non-classical.cert
    nonstd/workshops/1999/calculus/book/integral-rcfn.cert
    nonstd/workshops/1999/calculus/book/make-partition.cert
    nonstd/workshops/1999/calculus/book/map-rcfn-close-to-map-rcfn-refinement.cert
    nonstd/workshops/1999/calculus/book/map-rcfn-refinement-cdr-co-member.cert
    nonstd/workshops/1999/calculus/book/max-and-min-attained.cert
    nonstd/workshops/1999/calculus/book/max-x-between.cert
    nonstd/workshops/1999/calculus/book/maxlist-abslist-difflist-maps-lt.cert
    nonstd/workshops/1999/calculus/book/min-max-x-rec-lemmas.cert
    nonstd/workshops/1999/calculus/book/min-x-and-max-x-lemmas.cert
    nonstd/workshops/1999/calculus/book/min-x-between.cert
    nonstd/workshops/1999/calculus/book/next-gte-close.cert
    nonstd/workshops/1999/calculus/book/nsa-lemmas.cert
    nonstd/workshops/1999/calculus/book/nsa.cert
    nonstd/workshops/1999/calculus/book/partitions-give-i-close-riemann-sum.cert
    nonstd/workshops/1999/calculus/book/proof-outline.cert
    nonstd/workshops/1999/calculus/book/rcfn-next-gte-close.cert
    nonstd/workshops/1999/calculus/book/rcfn-standard-part.cert
    nonstd/workshops/1999/calculus/book/refinement-makes-i-small-change-1.cert
    nonstd/workshops/1999/calculus/book/refinement-makes-i-small-change.cert
    nonstd/workshops/1999/calculus/book/riemann-bound.cert
    nonstd/workshops/1999/calculus/book/riemann-defuns.cert
    nonstd/workshops/1999/calculus/book/riemann-lemmas.cert
    nonstd/workshops/1999/calculus/book/riemann-rcfn-between.cert
    nonstd/workshops/1999/calculus/book/riemann-rcfn-lower-bound.cert
    nonstd/workshops/1999/calculus/book/riemann-rcfn-refinement-is-riemann-rcfn.cert
    nonstd/workshops/1999/calculus/book/riemann-rcfn-upper-bound.cert
    nonstd/workshops/1999/calculus/book/riemann-sum-approximates-integral-1.cert
    nonstd/workshops/1999/calculus/book/riemann-sum-approximates-integral-2.cert
    nonstd/workshops/1999/calculus/book/riemann-sum-approximates-integral.cert
    nonstd/workshops/1999/calculus/book/riemann.cert
    nonstd/workshops/1999/calculus/book/split-integral-by-subintervals.cert
    nonstd/workshops/1999/calculus/book/standard-part-equal-if-i-close.cert
    nonstd/workshops/1999/calculus/book/standard-part-preserves-between.cert
    nonstd/workshops/1999/calculus/book/standard-part-riemann-rcfn-is-standard.cert
    nonstd/workshops/1999/calculus/book/two-times-r-is-not-less-than-standard-part.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/abs-derivative.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/chain-composition.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/composition-elem.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/differentiator.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/exp-minimal.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/exp-properties.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/inverse-composition.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/inverse-derivative.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/inverse-square.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/inverse-trig-derivatives.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/inverse-trig-ex.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/ln-derivative-real.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/nsa-ex.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/product-composition.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/sin-cos-minimal.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/sqrt-derivative.cert
    nonstd/workshops/2011/reid-gamboa-differentiator/support/sum-composition.cert
    nonstd/workshops/2013/helms-gamboa-quantum/support/quantum.cert
    projects/hybrid-systems/abs.cert projects/hybrid-systems/arith-nsa4.cert
    projects/hybrid-systems/computed-hints.cert
    projects/hybrid-systems/eexp.cert projects/hybrid-systems/example.cert
    projects/hybrid-systems/nsa.cert projects/hybrid-systems/o-real-p.cert
    projects/hybrid-systems/phi-exists.cert
    projects/hybrid-systems/phi-properties.cert
    projects/hybrid-systems/phi-unique.cert
    projects/hybrid-systems/tm-floor.cert ]
    Excluding books that depend on Quicklisp:
    [centaur/4v-sexpr/sexpr-purebool-p.cert centaur/4v-sexpr/top.cert
    centaur/aig/aig-sat-tests.cert centaur/aig/aig-sat.cert
    centaur/aig/faig-purebool-p.cert centaur/aig/top.cert
    centaur/esim/stv/stv-debug.cert centaur/esim/stv/stv2c/top.cert
    centaur/esim/tests/add.cert centaur/esim/tests/common.cert
    centaur/esim/tests/divide.cert centaur/esim/tests/idiv.cert
    centaur/esim/tests/multiply.cert centaur/esim/tests/regs.cert
    centaur/esim/tests/subtract.cert centaur/esim/tutorial/alu16-book.cert
    centaur/esim/tutorial/boothmul.cert centaur/esim/tutorial/counter.cert
    centaur/esim/tutorial/intro.cert centaur/esim/vcd/vcd-impl.cert
    centaur/esim/vcd/vcd.cert centaur/gl/bfr-satlink.cert
    centaur/gl/gl-ttags.cert centaur/misc/sharedlibtest/app.cert
    centaur/misc/tshell-tests.cert centaur/misc/tshell.cert
    centaur/quicklisp/base.cert centaur/quicklisp/bordeaux.cert
    centaur/quicklisp/bt-semaphore.cert centaur/quicklisp/cl-fad.cert
    centaur/quicklisp/external-program.cert centaur/quicklisp/fastnumio.cert
    centaur/quicklisp/html-template.cert centaur/quicklisp/hunchentoot.cert
    centaur/quicklisp/osicat.cert centaur/quicklisp/shellpool.cert
    centaur/quicklisp/top.cert centaur/quicklisp/uiop.cert
    centaur/satlink/benchmarks.cert centaur/satlink/check-config.cert
    centaur/satlink/top.cert centaur/sv/cosims/cosims.cert
    centaur/sv/tutorial/alu.cert centaur/sv/tutorial/boothpipe.cert
    centaur/vl/kit/gather.cert centaur/vl/kit/lint.cert centaur/vl/kit/pp.cert
    centaur/vl/kit/progutils.cert centaur/vl/kit/server.cert
    centaur/vl/kit/shell.cert centaur/vl/kit/top.cert centaur/vl/kit/zip.cert
    centaur/vl/server/file-layout.cert centaur/vl/server/server.cert
    centaur/vl2014/kit/gather.cert centaur/vl2014/kit/json.cert
    centaur/vl2014/kit/lint.cert centaur/vl2014/kit/model.cert
    centaur/vl2014/kit/pp.cert centaur/vl2014/kit/progutils.cert
    centaur/vl2014/kit/server.cert centaur/vl2014/kit/shell.cert
    centaur/vl2014/kit/top.cert centaur/vl2014/server/file-layout.cert
    centaur/vl2014/server/server.cert doc/top.cert oslib/copy.cert
    oslib/dirname.cert oslib/file-types.cert oslib/ls.cert oslib/mkdir.cert
    oslib/tests/copy.cert oslib/tests/dirname.cert oslib/tests/file-types.cert
    oslib/tests/ls.cert oslib/tests/mkdir.cert oslib/tests/top.cert
    oslib/top.cert projects/doc.cert projects/sidekick/eventdata.cert
    projects/sidekick/explore.cert projects/sidekick/lint.cert
    projects/sidekick/lock.cert projects/sidekick/lookup.cert
    projects/sidekick/server.cert projects/sidekick/session.cert
    projects/sidekick/top.cert projects/sidekick/webcommand.cert
    system/doc/acl2-manual.cert xdoc/all.cert xdoc/save-fancy.cert
    xdoc/save.cert ]
    if [ -d projects/milawa/ACL2 ] ; then \
    cd projects/milawa/ACL2;
    /Applications/Xcode.app/Contents/Developer/usr/bin/make clean ; \
    fi
    Using clean.pl to remove certificates, etc.
    Cleaning up Quicklisp files
    cd centaur/quicklisp; ./clean.sh
    /Users/boyer/acl2/books/build/clean.pl
    Cleaning centaur/vl/bin directory
    Cleaning centaur/vl2014/bin directory
    Calculating cert dependencies...
    Calculating pcert dependencies...
    Done with dependencies.
    Makefile:73: Makefile-deps: No such file or directory
    make[2]: *** No rule to make target `Makefile-deps'.
    make[2]: Failed to remake makefile `Makefile-deps'.
    Cleaning ACL2 directory (certificates, ACL2 images, etc.)
    clean.pl: scanning for generated files
    clean.pl: found 0 targets (0 seconds)
    clean.pl: deleted 0 files (0 seconds)
    Cleaning ../Proofs directory.
    make[1]: *** [milawa-clean] Error 2
    clean.pl: scanning for generated files
    clean.pl: found 18344 targets (2 seconds)
    clean.pl: deleted 18344 files (8 seconds)
    Cleaning quicklisp/bundle
    Cleaning asdf-home/cache/common-lisp
    Cleaning quicklisp books
    clean.pl: scanning for generated files
    clean.pl: found 0 targets (0 seconds)
    clean.pl: deleted 0 files (0 seconds)
    make[1]: Target `moreclean' not remade because of errors.
    make: *** [clean-books] Error 2

**Comment by jaredcdavis** [comment] 2015-06-04 02:11
I haven't been able to reproduce this.

From the log, it looks like we are running into an error in `projects/milawa/ACL2/Makefile` on line 73 where it tries to `include Makefile-deps`.  The `Makefile-deps` file ought to have been generated just a few lines above there in the call of `cert.pl`.

I can only grasp at straws as to how `Makefile-deps` would end up not existing.  The three main theories I can imagine are:

  1. Perhaps it was never created, e.g., `cert.pl` never wrote it out.
  2. Perhaps it was deleted after it was created but before it was included.
  3. Perhaps there is some kind of NFS or file system lag issue.

The third theory seems the least likely so lets discount it.

One thing that is suspicious: the `make` command at the top of the log appears to use `-j 4`.  I think this is going to be running the `acl2/GNUmakefile` target called `clean-books`, which invokes `$(MAKE)`, which AFAIK will essentially result in invoking `make -j 4 moreclean` in the `acl2/books` directory.

Probably there are not very many times that we ever execute `make -j 4 moreclean`, and perhaps there are problems doing so.  For instance, perhaps `cert.pl` can get confused if files are deleted by some other `make` process while it is scanning for dependencies, and if so perhaps this could cause it to fail to write `Makefile-deps`.  Alternately (though I think less likely), perhaps some other `make` process comes along and clobbers the `Makefile-deps` right after `cert.pl` has created it, while the `Makefile-pdeps` is being generated.

If you can figure out some way to reproduce this, you might try editing the `milawa/ACL2/Makefile` call of `cert.pl` to capture its output in some file and to make a copy of the resulting `Makefile-deps` that won't get deleted.  This might help to give us some clues as to what the problem might be.  But I can imagine this is hard to reprovoke...

**Comment by jaredcdavis** [comment] 2015-07-20 13:59
I'm going to close this until we can figure out how to reproduce it.

**Closed by jaredcdavis** 2015-07-20 13:59 UTC
Labels: bug, Component:Build
